### ISSUE TITLE
Add flag to build with integer-simple

### ISSUE THREAD

**Issue by michaelpj** [Bodigrim/mod#13]
It would be nice to have a flag to enable building with `integer-simple`, even if it was slower.

Reason for asking: HLS builds some static binaries on an alpine distribution that forces integer-simple in GHC.

**Comment by Bodigrim** [comment]
I made a separate release without `integer-gmp` dependency, https://hackage.haskell.org/package/mod-0.0.0.0. Does it help?

Moving forward, I'll switch future versions of `mod` to `ghc-bignum` to let GHC to choose a numeric backend.

**Comment by michaelpj** [comment]
Thanks! Let me see if that makes a difference. Using `ghc-bignum` does seem like the way of the future indeed.

**Comment by Bodigrim** [comment]
Fixed in 86e1e35.
