### ISSUE TITLE
`Show` instance

### ISSUE THREAD

**Issue by konsumlamm** [Bodigrim/mod#17]
I'm confused as to why the show instance always uses parentheses, e.g.:
```hs
 >>> -1 :: Mod 10
(9 `modulo` 10)
```
I'd expect that to only happen when the operator precedence requires it (using `showsPrec`). Furthermore, why is `modulo` used here? There is no function of that name in this package or in `base`. I think `mod` would be better here, as it mirrors [the `base` function](https://hackage.haskell.org/package/base-4.16.1.0/docs/Prelude.html#v:mod) and the math notation. I also would like something like "9 mod 10" (without the backticks), but the convention is to produce (more or less) valid Haskell expressions.

**Comment by Bodigrim** [comment]
`modulo` refers to https://hackage.haskell.org/package/arithmoi-0.12.0.1/docs/Math-NumberTheory-Moduli-Class.html#v:modulo
Admittedly it does not make much sense outside of `arithmoi` package. 

Dunno, maybe just print an underlying `Integer` naked?..
