### ISSUE TITLE
Behaviour of `Mod 0`

### ISSUE THREAD

**Issue by konsumlamm** [Bodigrim/mod#19]
Mathematically, ℤ/0ℤ is isomorphic to ℤ. I understand that implementing this behaviour here would require a lot of special casing and is probably not desirable.

However, even the way `Mod 0` is treated in this package is inconsistent. It is mostly treated as having no values, for example trying to construct a `Mod 0` with `fromInteger` always fails with an exception. However, e.g. `zero` is unconditionally defined as `Mod 0`, so that `zero :: Mod 0` is a valid (non-bottom) value.

I'm not sure what the best way to address this is. One possibility is to add a bunch of `1 <= m` constraints (which is what the `modular-arithmetic` package does for example). Another possibility would be to simply document that the `Mod 0` type shouldn't be used.

**Comment by Bodigrim** [comment]
Good point. I've addressed inconsistencies in 4f907d36f31fe4b9688dc9d241480aa8acba05e3, feel free to improve documentation.

I'm reluctant to go for `1 <= m`, because it breaks all users and because GHC UX with type level comparisons is not great.
