### ISSUE TITLE
Understanding the `GcdDomain`, `Euclidean`, `Field` instances

### ISSUE THREAD

**Issue by konsumlamm** [Bodigrim/mod#20]
### GcdDomain

`divide` returns a `Maybe (Mod m)`, so why does it always return `Just (x / y)`, even when `y` is not invertible? I also don't really understand why `gcd`/`lcm` are defined to always be 1, is this just an arbitrary choice (assuming that every element is invertible)?

### Euclidean

Again, why does `rem x y` always return 0, when not every `y` is invertible? Is there even a definition of remainder that makes sense for integers modulo m?

### Field

ℤ/mℤ is a field if and only if m is prime, so I think that should at least be documented. Adding an `IsPrime m` constraint would probably be too expensive.

**Comment by Bodigrim** [comment]
Strcitly speaking, any GCD domain is an integral domain without zero divisors. So even `instance GcdDomain (Mod m)` morally requires `IsPrime m`. It would be nice to document this.

Let me see if I can come up with a better definition for `instance GcdDomain (Mod m)` however, which at least tries to do something sensible when `m` is composite.

**Comment by Bodigrim** [comment]
I took a stab in de9ef6aa1eef73de459851100aed8bc021ac86e6, but it's not completed yet.

**Comment by Bodigrim** [comment]
And one more patch: 301f911

@konsumlamm how does it look? is it making more sense now?

**Comment by konsumlamm** [comment]
That's much better! I'm not sure what you mean by "`divide` returns any of quotients" though?

These modifications should also be applied to `Data.Mod.Word`.

**Comment by konsumlamm** [comment]
I see you defined `divide (Mod 0) _ = Just (Mod 0)`, I don't think this should be the case if the second argument is not invertible (e.g. now `divide 0 0` is 0).

**Comment by Bodigrim** [comment]
Well, `divide x y` returns any `z` such that `x == y * z`, if such numbers exist, and `Nothing` otherwise. 
https://github.com/Bodigrim/mod/blob/301f911d417fd3981bb911e4708ff4db16aa4330/test/Test.hs#L335-L338
From this viewpoint `divide 0 0 = Just 0` is fine. The justification is that I can live with `{quot,div,rem,mod} :: a -> a -> a` throwing exceptions, because the type signature gives them no other options, but to throw `DivideByZero` from `divide :: a -> a -> Maybe a` is really weird.

**Comment by konsumlamm** [comment]
> Well, `divide x y` returns any `z` such that `x == y * z`, if such numbers exist, and `Nothing` otherwise.
> 
> https://github.com/Bodigrim/mod/blob/301f911d417fd3981bb911e4708ff4db16aa4330/test/Test.hs#L335-L338
> 
> From this viewpoint `divide 0 0 = Just 0` is fine. The justification is that I can live with `{quot,div,rem,mod} :: a -> a -> a` throwing exceptions, because the type signature gives them no other options, but to throw `DivideByZero` from `divide :: a -> a -> Maybe a` is really weird.

I see your point, but with the current design, even `quot` returns 0 for `quot 0 0`, rather than throwing `DivideByZero`.

**Comment by konsumlamm** [comment]
Oh, also, can you explain what the change in `divide`/`quotRem` (to divide by the gcd of `m` and `y`) is for?

**Comment by Bodigrim** [comment]
> I see your point, but with the current design, even `quot` returns 0 for `quot 0 0`, rather than throwing `DivideByZero`.

This way `quotRem` matches `divide` and does not violate laws of `Euclidean`.

> Oh, also, can you explain what the change in `divide`/`quotRem` (to divide by the gcd of `m` and `y`) is for?

There is no inverse of `2 :: Mod 10`, but you can still assign a value to ``6 `divide` 2 :: Maybe (Mod 3)`` in the sense described above.
